### ISSUE TITLE
enumFromThen broken?

### ISSUE THREAD

**Issue by moll** [mvv/data-dword#2]
Hi!

Thanks for the handy library!
Is it me or is `enumFromThen` (`[0x20, 0x40..]`) broken and returning an empty list?
```
Prelude Data.DoubleWord> take 5 $ (enumFromThen 0x20 0x40) :: [Word256]
[]
it :: [Word256]
Prelude Data.DoubleWord> take 5 $ (enumFromThenTo 0x20 0x40 0x100) :: [Word256]
[32,64,96,128,160]
it :: [Word256]
```

**Comment by moll** [comment]
Looking at https://github.com/mvv/data-dword/blob/8cdf404eccf6b18d8a345e002840c7cfa8bd7050/src/Data/DoubleWord/TH.hs#L227-L237 I can see it's supposed to delegate to `enumFromThenTo` with `maxBound`. Could it be that the args given to `(appVN '(>=) [x, y])` are backwards?

**Comment by mvv** [comment]
Thanks for the report. Fixed and uploaded to Hackage.
